---
- hosts: rhs_servers
  remote_user: root
  gather_facts: no       # For now do not gather facts, but would like to gather
                         # facts and use the disks from gathered facts

  tasks:
  - name: Create volume group on the disks
    vg: action="create" disks={{ item.brick }}
        options="--physicalextentsize 128k"
        vgname={{ item.vg }}
    with_items: vgnames
